#pragma once

#include <stdint.h>

#define BIT0(n)  static_cast<bool>(n & (1 <<  0))
#define BIT1(n)  static_cast<bool>(n & (1 <<  1))
#define BIT2(n)  static_cast<bool>(n & (1 <<  2))
#define BIT3(n)  static_cast<bool>(n & (1 <<  3))
#define BIT4(n)  static_cast<bool>(n & (1 <<  4))
#define BIT5(n)  static_cast<bool>(n & (1 <<  5))
#define BIT6(n)  static_cast<bool>(n & (1 <<  6))
#define BIT7(n)  static_cast<bool>(n & (1 <<  7))
#define BIT8(n)  static_cast<bool>(n & (1 <<  8))
#define BIT9(n)  static_cast<bool>(n & (1 <<  9))
#define BIT10(n) static_cast<bool>(n & (1 << 10))
#define BIT11(n) static_cast<bool>(n & (1 << 11))
#define BIT12(n) static_cast<bool>(n & (1 << 12))
#define BIT13(n) static_cast<bool>(n & (1 << 13))
#define BIT14(n) static_cast<bool>(n & (1 << 14))
#define BIT15(n) static_cast<bool>(n & (1 << 15))
#define BIT16(n) static_cast<bool>(n & (1 << 16))
#define BIT17(n) static_cast<bool>(n & (1 << 17))
#define BIT18(n) static_cast<bool>(n & (1 << 18))
#define BIT19(n) static_cast<bool>(n & (1 << 19))
#define BIT20(n) static_cast<bool>(n & (1 << 20))
#define BIT21(n) static_cast<bool>(n & (1 << 21))
#define BIT22(n) static_cast<bool>(n & (1 << 22))
#define BIT23(n) static_cast<bool>(n & (1 << 23))
#define BIT24(n) static_cast<bool>(n & (1 << 24))
#define BIT25(n) static_cast<bool>(n & (1 << 25))
#define BIT26(n) static_cast<bool>(n & (1 << 26))
#define BIT27(n) static_cast<bool>(n & (1 << 27))
#define BIT28(n) static_cast<bool>(n & (1 << 28))
#define BIT29(n) static_cast<bool>(n & (1 << 29))
#define BIT30(n) static_cast<bool>(n & (1 << 30))
#define BIT31(n) static_cast<bool>(n & (1 << 31))
#define BIT32(n) static_cast<bool>(n & (1 << 32))

#define BITFIELD_UINT16(n, msb, lsb) (static_cast<uint16_t>(n & (static_cast<uint16_t>(0xffff << (15 - msb)) >> static_cast<uint16_t>(15 - msb + lsb) << lsb)) >> static_cast<uint16_t>(lsb))
#define BITFIELD_UINT32(n, msb, lsb) (static_cast<uint32_t>(n & (static_cast<uint32_t>(0xffffffff << (31 - msb)) >> static_cast<uint32_t>(31 - msb + lsb) << lsb)) >> static_cast<uint32_t>(lsb))
